name: Dialyzer

env:
  ELIXIR_VERSION: "1.12.0"
  MIX_ENV: dev
  OTP_VERSION: "24.0"

on:
  push:
    branches:
      - "**"

jobs:
  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - uses: actions/cache@v2.1.6
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - uses: actions/cache@v2.1.6
        with:
          path: _build/test
          key: ${{ runner.os }}-test-build
          restore-keys: |
            ${{ runner.os }}-test-build
      - name: Install Dependencies
        run: mix deps.get
      - name: Retrieve PLT Cache
        uses: actions/cache@v2.1.6
        id: plt-cache
        with:
          path: priv/plts
          key: ${{ runner.os }}-dialyzer-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mix dialyzer --plt

      - name: Run dialyzer
        run: mix dialyzer --no-check --halt-exit-status
